### ISSUE TITLE
Chest Animation Glitch

### ISSUE THREAD

**Issue by Tikkle** [SquaredHelix/VanillaPlus#2]
**Describe the bug**
Just a visual glitch, the chests stay open when clicking the item frame to open them.

**To Reproduce**
1. Download VanillaPlus 1.3.2
2. PaperMC 1.16.1 server
3. Place item frame on chest
4. Put an item in the item frame
5. Right-click item frame to open the chest

**Expected behavior**
Chest to open and close.

**Screenshots**
[https://imgur.com/eDyP7Ht](https://imgur.com/eDyP7Ht)

**Server**
 - Java version: Java 8
 - Minecraft version: git-Paper-131 (1.16.1-R0.1-SNAPSHOT)
 - Plugin version: 1.3.2
 - OS: Linux

**Comment by SquaredHelix** [comment]
This seems to be a 1.16 issue. It only happens with double chests. I found a hacky way to fix it by calling Chest.open and then Chest.close on both halves of the double chest. When I first tested the open/close methods it did not work. It may be that my jar was mislabelled to 1.16.1, but I updated using BuildTools (for regular Spigot) and I am now at git-Spigot-9639cf7-f622793. According to [Paper Javadocs](https://papermc.io/javadocs/paper/1.16/org/bukkit/block/Chest.html), this change is already merged for paper.
Fixed this in fca0e2b3c3cb49473116f5481f0b3a3b1e46b3a8
This should be included in the next release

Thank you for the report
