### ISSUE TITLE
NoStrip not working

### ISSUE THREAD

**Issue by Tikkle** [SquaredHelix/VanillaPlus#4]
**Describe the bug**
When right-clicking non-stripped logs, they become stripped.

**To Reproduce**
1. Install VanillaPlus 1.3.3
2. Right-click log

**Expected behavior**
Log to remain in its non-stripped form.

**Screenshots**
[https://gyazo.com/6e4fdccfa65fde110669d0a641a71ce1](https://gyazo.com/6e4fdccfa65fde110669d0a641a71ce1)

**Server**
 - Java version: 8
 - Minecraft version: 1.16.1
 - Plugin version: 1.3.3
 - OS: Linux

**Additional context**

**Comment by SquaredHelix** [comment]
I forgot to add the Netherite Axe when updating the plugin to 1.16. 4b2c2306483b692b031ac6dde5b7701da8eaaf10
Will be included in next release

**Comment by SquaredHelix** [comment]
In addition to this, I also added the two new log types from 1.16 to the module. fbb062279b10445dd642a87ea5c8a67393bc3b9f

**Comment by Tikkle** [comment]
In addition to this bug, you cannot use a netherite axe in the stripped log crafting recipe to make stripped logs.

**Comment by SquaredHelix** [comment]
See the latest build (1.3.4), should fix this
